USE color4rit;

CREATE TABLE IF NOT EXISTS jogador (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255),
  login VARCHAR(255),
  senha VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS musica (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255),
  autor VARCHAR(255),
  duracao INT
);

CREATE TABLE IF NOT EXISTS mapa (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dificuldade VARCHAR(50),
  fk_musica BIGINT UNSIGNED,
  FOREIGN KEY (fk_musica) REFERENCES musica(id)
);

CREATE TABLE IF NOT EXISTS nota (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fk_mapa BIGINT UNSIGNED,
  cor VARCHAR(50),
  tempo TIME,
  FOREIGN KEY (fk_mapa) REFERENCES mapa(id)
);

CREATE TABLE IF NOT EXISTS placar (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  pontuacao INT,
  fk_jogador BIGINT UNSIGNED,
  fk_musica BIGINT UNSIGNED,
  FOREIGN KEY (fk_jogador) REFERENCES jogador(id),
  FOREIGN KEY (fk_musica) REFERENCES musica(id)
);
