USE COLOR4RIT;

SELECT * FROM MUSICA;

INSERT INTO MUSICA (MUSICA, NOME, AUTOR) 
VALUES ('00:05:36', 'TROPA DO KÜSTERVERSO', 'LOREN TRALHA');

SELECT * FROM NOTA;

INSERT INTO NOTA (FK_ID_MAPA, COR, TEMPO) 
VALUES (1, 'AZUL', '00:00:15');

SELECT * FROM MAPA;

INSERT INTO MAPA (DIFICULDADE, FK_ID_MUSICA) 
VALUES ('FÁCIL', 1);

SELECT * FROM PLACAR;

INSERT INTO PLACAR (PONTUACAO, FK_ID_JOGADOR, FK_ID_MUSICA) 
VALUES (300, 1, 1);

SELECT * FROM JOGADOR;

INSERT INTO JOGADOR (NOME, LOGIN, SENHA) 
VALUES ('João', 'joao@email.com', 'senha123');

UPDATE MUSICA 
SET NOME = 'Nova Música' 
WHERE ID = 1;

UPDATE PLACAR 
SET PONTUACAO = 400 
WHERE ID = 1;

UPDATE JOGADOR 
SET NOME = 'Novo Nome' 
WHERE ID = 1;

UPDATE MAPA
SET DIFICULDADE = 'NOVA DIFICULDADE'
WHERE ID = 1;

DELETE FROM MUSICA WHERE ID = 1;

DELETE FROM NOTA 
WHERE ID = 1;

DELETE FROM MAPA 
WHERE ID = 1;

DELETE FROM PLACAR 
WHERE ID = 1;

DELETE FROM JOGADOR 
WHERE ID = 1;
