USE color4rit;
-- Deixar como minuscula

SELECT * FROM JOGADOR;

INSERT INTO JOGADOR (NOME, LOGIN, SENHA)
VALUES ('Admin', 'admin@admin.com', 'color#1234');


SELECT * FROM MUSICA;

INSERT INTO MUSICA (DURACAO, NOME, AUTOR)
VALUES ('00:02:55','TROPA DO KÜSTERVERSO', 'LOREN TRALHA');


SELECT * FROM MAPA;

INSERT INTO MAPA (DIFICULDADE, FK_MUSICA)
VALUES ('FACIL', 1);


SELECT * FROM NOTA;

INSERT INTO NOTA (FK_MAPA, COR, TEMPO)
VALUES (1, 'AZUL', '00:00:15');


SELECT * FROM PLACAR;

INSERT INTO PLACAR (PONTUACAO, FK_JOGADOR, FK_MUSICA)
VALUES (300, 1, 1);



UPDATE MUSICA 
SET NOME = 'Nova Música' 
WHERE ID = 1;

UPDATE PLACAR 
SET PONTUACAO = 400 
WHERE ID = 1;

UPDATE JOGADOR 
SET NOME = 'Novo Nome' 
WHERE ID = 1;

UPDATE MAPA
SET DIFICULDADE = 'NOVA DIFICULDADE'
WHERE ID = 1;

DELETE FROM MUSICA WHERE ID = 1;

DELETE FROM NOTA 
WHERE ID = 1;

DELETE FROM MAPA 
WHERE ID = 1;

DELETE FROM PLACAR 
WHERE ID = 1;

DELETE FROM JOGADOR 
WHERE ID = 1;
