USE color4rit;


SELECT * FROM JOGADOR;

INSERT INTO JOGADOR (NOME, LOGIN, SENHA) 
VALUES ('Admin', 'admin@admin.com', 'color#1234');


SELECT * FROM MUSICA;

INSERT INTO MUSICA (DURACAO, NOME, AUTOR)
VALUES (192000,'Loretta', 'Ginger Root');

INSERT INTO MUSICA (DURACAO, NOME, AUTOR)
VALUES (176000,'Into the Beat City', 'Tadeu Moura');

INSERT INTO MUSICA (DURACAO, NOME, AUTOR)
VALUES (125000,'Universal Exploration', 'Tadeu Moura');

INSERT INTO MUSICA (DURACAO, NOME, AUTOR)
VALUES (166000,'Trifonia Of Moonlight', 'Tadeu Moura');


SELECT * FROM MAPA;

--Loretta
INSERT INTO MAPA (DIFICULDADE, FK_MUSICA)
VALUES ('FACIL', 1);

INSERT INTO MAPA (DIFICULDADE, FK_MUSICA)
VALUES ('MEDIO', 1);

INSERT INTO MAPA (DIFICULDADE, FK_MUSICA)
VALUES ('DIFICIL', 1);

--Into the Beat City
INSERT INTO MAPA (DIFICULDADE, FK_MUSICA)
VALUES ('FACIL', 2);

INSERT INTO MAPA (DIFICULDADE, FK_MUSICA)
VALUES ('MEDIO', 2);

INSERT INTO MAPA (DIFICULDADE, FK_MUSICA)
VALUES ('DIFICIL', 2);

--Universal Exploration
INSERT INTO MAPA (DIFICULDADE, FK_MUSICA)
VALUES ('FACIL', 3);

INSERT INTO MAPA (DIFICULDADE, FK_MUSICA)
VALUES ('MEDIO', 3);

INSERT INTO MAPA (DIFICULDADE, FK_MUSICA)
VALUES ('DIFICIL', 3);

--Trifonia Of Moonlight
INSERT INTO MAPA (DIFICULDADE, FK_MUSICA)
VALUES ('FACIL', 4);

INSERT INTO MAPA (DIFICULDADE, FK_MUSICA)
VALUES ('MEDIO', 4);

INSERT INTO MAPA (DIFICULDADE, FK_MUSICA)
VALUES ('DIFICIL', 4);


SELECT * FROM NOTA;
SELECT * FROM NOTA WHERE STATUS = 1; -- pega apenas valores ativos

INSERT INTO NOTA (FK_MAPA, COR, TEMPO, STATUS) 
VALUES (1, 'VERMELHO', 12000, 1);


SELECT * FROM PLACAR;

INSERT INTO PLACAR (PONTUACAO, FK_JOGADOR, FK_MAPA, DATA_INI)
VALUES (200, 1, 1, '2024-05-14 12:12:45');


UPDATE NOTA
SET STATUS = 0
WHERE ID = 3;

UPDATE MUSICA 
SET NOME = 'Loretta',
AUTOR = 'Ginger Root'
WHERE ID = 1;

UPDATE PLACAR 
SET PONTUACAO = 400 
WHERE ID = 1;

UPDATE JOGADOR 
SET NOME = 'Novo Nome' 
WHERE ID = 1;

UPDATE MAPA
SET DIFICULDADE = 'NOVA DIFICULDADE'
WHERE ID = 1;

DELETE FROM MUSICA WHERE ID = 1;

DELETE FROM NOTA 
WHERE ID = 1;

DELETE FROM MAPA 
WHERE ID = 1;

DELETE FROM PLACAR 
WHERE ID = 1;

DELETE FROM JOGADOR 
WHERE ID = 1;
